// WASM façade loader — lazy-imports the wasm-bindgen shim and
// caches the initialised module so every caller after the first one
// gets the same Promise.
//
// Per ADR-017 strangler-fig step 8 + foundation issue #33: this is
// the one place the FE talks to `crates/wasm/`. Layouts, the print
// tab, and any future preflight hook all import from this module so
// the WASM init story is centralised.
//
// The shim itself (`part_registry_wasm.js`) is regenerated by
// `npm run build:wasm` (which delegates to `wasm-pack build
// crates/wasm --target web --out-dir web/src/wasm`). The `.wasm`
// binary sits next to the JS shim and is fetched relative to the
// Vite-bundled JS, so deployment to GitHub Pages picks it up
// automatically via Vite's asset hashing.

import init, {
  initSync,
  render_label as wasmRenderLabel,
  validate_diff as wasmValidateDiff,
  classify_diff as wasmClassifyDiff,
  policy_decision as wasmPolicyDecision,
  recommend_format as wasmRecommendFormat,
  check_format_warning as wasmCheckFormatWarning,
} from "./part_registry_wasm";
// Vite-friendly URL import: the bundler emits the .wasm as a
// fingerprinted asset and gives us back the URL to fetch at runtime.
// This avoids the default behaviour of resolving the path relative
// to the JS shim, which breaks under GitHub Pages' base path.
import wasmUrl from "./part_registry_wasm_bg.wasm?url";

/**
 * Layout identifier accepted by `renderLabel`. Mirrors the
 * Python `label.py` --layout flag values verbatim.
 */
export type WasmLayoutId = "vert" | "horz" | "flag";

/**
 * Text-format identifier accepted by `renderLabel`. Mirrors the
 * Python `label.py` --format flag values verbatim.
 */
export type WasmFormatId = "4/4" | "4/4/4" | "5/5/4";

/** One advisory finding from `validateDiff`. */
export interface Violation {
  kind: string;
  message: string;
}

/** Structured result returned by `validateDiff`. */
export interface ValidateResult {
  ok: boolean;
  violations: Violation[];
}

/** ADR-016 §"Semantic change classes" classifier output. */
export interface Action {
  kind: string;
  [key: string]: unknown;
}

/** ADR-020 §"AuthDecision" decision shape. */
export type AuthDecision =
  | { kind: "allow" }
  | { kind: "warn"; reason: string }
  | { kind: "requires_elevation"; approver_role: string }
  | { kind: "block"; reason: string };

type WasmModule = {
  renderLabel: typeof wasmRenderLabel;
  validateDiff: typeof wasmValidateDiff;
  classifyDiff: typeof wasmClassifyDiff;
  policyDecision: typeof wasmPolicyDecision;
  recommendFormat: typeof wasmRecommendFormat;
  checkFormatWarning: typeof wasmCheckFormatWarning;
};

let pending: Promise<WasmModule> | null = null;
let ready: WasmModule | null = null;

/**
 * Initialise the WASM module on first call; return the cached
 * binding on every call after. Idempotent. Safe to call in parallel.
 *
 * Callers that want synchronous access (e.g. the layout `renderSvg`
 * surface, which is structurally sync) should `await loadWasm()`
 * once at app boot and then use the `*Sync` helpers below.
 */
export function loadWasm(): Promise<WasmModule> {
  if (pending) return pending;
  pending = init({ module_or_path: wasmUrl }).then(() => {
    ready = {
      renderLabel: wasmRenderLabel,
      validateDiff: wasmValidateDiff,
      classifyDiff: wasmClassifyDiff,
      policyDecision: wasmPolicyDecision,
      recommendFormat: wasmRecommendFormat,
      checkFormatWarning: wasmCheckFormatWarning,
    };
    return ready;
  });
  return pending;
}

/**
 * Has the WASM module finished initialising? Cheap synchronous
 * check used by call sites that fall back to a placeholder if the
 * label can't be rendered yet.
 */
export function isWasmReady(): boolean {
  return ready !== null;
}

/**
 * Synchronous init from a pre-fetched byte buffer. Used by tests
 * (vitest / node) where `init()`'s `fetch(URL)` path isn't available.
 * Caches the module identically to `loadWasm`.
 */
export function initWasmFromBytes(bytes: BufferSource): void {
  if (ready) return;
  initSync({ module: bytes });
  ready = {
    renderLabel: wasmRenderLabel,
    validateDiff: wasmValidateDiff,
    classifyDiff: wasmClassifyDiff,
    policyDecision: wasmPolicyDecision,
    recommendFormat: wasmRecommendFormat,
    checkFormatWarning: wasmCheckFormatWarning,
  };
  pending = Promise.resolve(ready);
}

function requireReady(): WasmModule {
  if (!ready) {
    throw new Error(
      "part-registry-wasm: call loadWasm() once during app boot before " +
        "using the synchronous render/validate helpers (layouts call " +
        "renderLabelSync; ensure main.ts awaits loadWasm()).",
    );
  }
  return ready;
}

/** Synchronous `renderLabel`. Requires `await loadWasm()` to have completed. */
export function renderLabelSync(
  canonical: string,
  layout: WasmLayoutId,
  sizeMm: number,
  format: WasmFormatId,
  options: {
    micro?: boolean;
    cableOdMm?: number;
    noMarkers?: boolean;
    alignmentLine?: boolean;
  } = {},
): string {
  return requireReady().renderLabel(
    canonical,
    layout,
    sizeMm,
    format,
    options.micro ?? false,
    options.cableOdMm ?? 0,
    options.noMarkers ?? false,
    options.alignmentLine ?? false,
  );
}

/** Synchronous `validateDiff`. Requires `await loadWasm()` to have completed. */
export function validateDiffSync(input: unknown): ValidateResult {
  return requireReady().validateDiff(JSON.stringify(input)) as ValidateResult;
}

/** Synchronous `classifyDiff`. Requires `await loadWasm()` to have completed. */
export function classifyDiffSync(diff: unknown): Action[] {
  return requireReady().classifyDiff(JSON.stringify(diff)) as Action[];
}

/** Synchronous `policyDecision`. Requires `await loadWasm()` to have completed. */
export function policyDecisionSync(input: {
  diff: unknown;
  operator: unknown;
  policy?: unknown;
}): AuthDecision {
  return requireReady().policyDecision(JSON.stringify(input)) as AuthDecision;
}

/**
 * Render an SVG label via the Rust codec.
 *
 * Synchronous from the caller's perspective: returns a Promise that
 * resolves to the SVG string. The Promise resolves immediately
 * (microtask) after the first call's `init()` completes.
 *
 * `cableOdMm` is consumed only by the `flag` layout; passing `0` for
 * vert/horz falls through to the Python default of 6 mm.
 */
export async function renderLabel(
  canonical: string,
  layout: WasmLayoutId,
  sizeMm: number,
  format: WasmFormatId,
  options: {
    micro?: boolean;
    cableOdMm?: number;
    noMarkers?: boolean;
    alignmentLine?: boolean;
  } = {},
): Promise<string> {
  const wasm = await loadWasm();
  return wasm.renderLabel(
    canonical,
    layout,
    sizeMm,
    format,
    options.micro ?? false,
    options.cableOdMm ?? 0,
    options.noMarkers ?? false,
    options.alignmentLine ?? false,
  );
}

/** Run all structural validators. Advisory per ADR-016. */
export async function validateDiff(input: unknown): Promise<ValidateResult> {
  const wasm = await loadWasm();
  return wasm.validateDiff(JSON.stringify(input)) as ValidateResult;
}

/** Classify a `Diff` per ADR-016 §"Semantic change classes". */
export async function classifyDiff(diff: unknown): Promise<Action[]> {
  const wasm = await loadWasm();
  return wasm.classifyDiff(JSON.stringify(diff)) as Action[];
}

/**
 * Run the policy engine. `input = { diff, operator, policy? }`.
 * Returns the strongest `AuthDecision` across all classified
 * actions per ADR-016 §"Policy model".
 */
export async function policyDecision(input: {
  diff: unknown;
  operator: unknown;
  policy?: unknown;
}): Promise<AuthDecision> {
  const wasm = await loadWasm();
  return wasm.policyDecision(JSON.stringify(input)) as AuthDecision;
}

/** Recommend a text-format for a given size; mirrors `label.py:recommend_format`. */
export async function recommendFormat(
  sizeMm: number,
): Promise<{ format: WasmFormatId; warning: string | null }> {
  const wasm = await loadWasm();
  return wasm.recommendFormat(sizeMm) as {
    format: WasmFormatId;
    warning: string | null;
  };
}

/** Warn if a (size, format) pair is sub-optimal; mirrors `label.py:check_format_warning`. */
export async function checkFormatWarning(
  sizeMm: number,
  format: WasmFormatId,
): Promise<string | undefined> {
  const wasm = await loadWasm();
  return wasm.checkFormatWarning(sizeMm, format);
}
