// Shared SVG primitives — DRY: every layout calls these instead of
// inlining XML strings. Keep the QR matrix generation centralized so
// any change (encoding, error level, quiet zone) lands in one place.
//
// QR matrix is generated by the dynamically-imported segno via a JS
// QR encoder (qr-code-generator-style). For the spike we use a small
// pure-JS encoder since segno is Python-only.

import { QR_BORDER_MODULES } from "../config";

// Pure-JS QR encoder — qrcode-generator (MIT) inlined to avoid an
// extra runtime dep for the spike. Replaceable with Pyodide-loaded
// segno once that path lands.
import qrcode from "./qrcode-generator";

export function svgWrap(wMm: number, hMm: number, body: string): string {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" ` +
    `width="${wMm.toFixed(3)}mm" height="${hMm.toFixed(3)}mm" ` +
    `viewBox="0 0 ${wMm.toFixed(3)} ${hMm.toFixed(3)}">\n${body}\n</svg>`
  );
}

export function qrBlock(canonical: string, x: number, y: number, size: number): string {
  // Error correction "M" (~15%), auto type/version. Matches label.py.
  const qr = qrcode(0, "M");
  qr.addData(canonical);
  qr.make();
  const n = qr.getModuleCount();
  const totalModules = n + 2 * QR_BORDER_MODULES;
  const module = size / totalModules;
  const rects: string[] = [];
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      if (qr.isDark(r, c)) {
        const rx = x + (c + QR_BORDER_MODULES) * module;
        const ry = y + (r + QR_BORDER_MODULES) * module;
        rects.push(
          `<rect x="${rx.toFixed(3)}" y="${ry.toFixed(3)}" ` +
            `width="${module.toFixed(3)}" height="${module.toFixed(3)}" fill="#000"/>`,
        );
      }
    }
  }
  return rects.join("\n");
}

export function textBlock(canonical: string, x: number, y: number, size: number): string {
  const rows = [canonical.slice(0, 4), canonical.slice(4, 8), canonical.slice(8, 12)];
  const innerH = size * 0.8;
  const font = innerH / 3.6;
  const gap = font * 0.3;
  const cx = x + size / 2;
  const y0 = y + (size - innerH) / 2 + font * 0.85;
  // Mirror label.py text_block: bold font + thin black stroke for
  // legibility at <2 mm. Without the stroke, bold is only synthetic on
  // most rendering pipelines and the gain is marginal.
  const strokeW = font * 0.03;
  return rows
    .map(
      (row, i) =>
        `<text x="${cx.toFixed(3)}" y="${(y0 + i * (font + gap)).toFixed(3)}" ` +
        `font-family="Courier Bold, Courier New, Courier, monospace" ` +
        `font-weight="700" font-size="${font.toFixed(3)}" ` +
        `stroke="#000" stroke-width="${strokeW.toFixed(3)}" ` +
        `text-anchor="middle" fill="#000">${row}</text>`,
    )
    .join("\n");
}
